image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-ibank-build-for-testers.jar" -PassThru

build_script:
  - chmod +x gradlew
  - ./gradlew test --info '-Dselenide.headless=true'